### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by clopasto** [wesbarnett/libgmxfort#1]
Dear Wes Barnett,
we are really intersted in your code. We cloned it, download and compiled 
libxdrfile, but we get this error when compiling libgmxfort:

[ 14%] Building Fortran object CMakeFiles/gmxfort.dir/src/indexfile.f90.o
/home/pastorin/programs/GROMACS/read_write_gromacs_f90/libgmxfort/src/indexfile.f90:117:21:

             allocate(this%group(I)%LOC, source=INDICES_TMP(1:this%group(I)%NUMATOMS))
                     1
Error: Array specification required in ALLOCATE statement at (1)
CMakeFiles/gmxfort.dir/build.make:110: recipe for target 'CMakeFiles/gmxfort.dir/src/indexfile.f90.o' failed
make[3]: *** [CMakeFiles/gmxfort.dir/src/indexfile.f90.o] Error 1
CMakeFiles/gmxfort.dir/build.make:126: recipe for target 'CMakeFiles/gmxfort.dir/src/indexfile.f90.o.provides' failed
make[2]: *** [CMakeFiles/gmxfort.dir/src/indexfile.f90.o.provides] Error 2
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/gmxfort.dir/all' failed
make[1]: *** [CMakeFiles/gmxfort.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Do you have any educated suggestion? 

Thanks in advance !
Claudio

**Comment by wesbarnett** [comment]
Hi @clopasto, thanks for filing an issue. Glad someone is interested in using the code.

Do you know what compiler (including version) you are using?

**Comment by wesbarnett** [comment]
I actually just tested with a slightly older compiler and had the same error message. I've committed a change which I think fixes your issue. Update your local version and let me know if it fixes it.

**Comment by clopasto** [comment]
Hi Wes,
I did update the local version and the problems seem to be solved! 
The code  compiled perfectly and 'make test' gave a successful output. 
Thanks a lot and let you know our use of your code! 
Best,
Claudio
