### ISSUE TITLE
Fortran example in ./example does not compile

### ISSUE THREAD

**Issue by clopasto** [wesbarnett/libgmxfort#2]
Dear Wes Barnett,
the code compiles perfectly. Tests and installation seem to be successful. 
But we cannot compile the example in ./example. 

These are the errors we get:

 make
/tmp/ccrAlDlQ.o: In function `MAIN__':
main.f90:(.text+0x37): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x72): undefined reference to `__gmxfort_trajectory_MOD_trajectory_read'
main.f90:(.text+0x81): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0xa5): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_natoms'
main.f90:(.text+0x300): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x382): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_xyz'
main.f90:(.text+0x3b4): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x445): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_xyz'
main.f90:(.text+0x47a): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x50b): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_xyz'
main.f90:(.text+0x540): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x5d1): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_xyz'
main.f90:(.text+0x606): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x697): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_box'
main.f90:(.text+0x738): undefined reference to `__gmxfort_utils_MOD_dihedral_angle'
main.f90:(.text+0x987): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x9c2): undefined reference to `__gmxfort_trajectory_MOD_trajectory_read'
main.f90:(.text+0x9d1): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x9f5): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_natoms'
main.f90:(.text+0xc50): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0xcd0): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_xyz'
main.f90:(.text+0xd02): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0xd91): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_xyz'
main.f90:(.text+0xdc6): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0xe55): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_xyz'
main.f90:(.text+0xe8a): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0xf19): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_xyz'
main.f90:(.text+0xf4e): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0xfdf): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_box'
main.f90:(.text+0x1080): undefined reference to `__gmxfort_utils_MOD_dihedral_angle'
main.f90:(.text+0x12cf): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x12fe): undefined reference to `__gmxfort_trajectory_MOD_trajectory_open'
main.f90:(.text+0x1309): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x132d): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_natoms'
main.f90:(.text+0x154a): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x1573): undefined reference to `__gmxfort_trajectory_MOD_trajectory_read_next'
main.f90:(.text+0x15a4): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x162a): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_xyz'
main.f90:(.text+0x165c): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x16f1): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_xyz'
main.f90:(.text+0x1726): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x17bb): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_xyz'
main.f90:(.text+0x17f0): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x1885): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_xyz'
main.f90:(.text+0x18ba): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x1949): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_box'
main.f90:(.text+0x19ea): undefined reference to `__gmxfort_utils_MOD_dihedral_angle'
main.f90:(.text+0x1be5): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x1bff): undefined reference to `__gmxfort_trajectory_MOD_trajectory_close'
main.f90:(.text+0x1c40): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x1c6f): undefined reference to `__gmxfort_trajectory_MOD_trajectory_open'
main.f90:(.text+0x1c7a): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x1c9e): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_natoms'
main.f90:(.text+0x1ecc): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x1ef5): undefined reference to `__gmxfort_trajectory_MOD_trajectory_read_next'
main.f90:(.text+0x1f3a): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x1fbc): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_xyz'
main.f90:(.text+0x1fee): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x207f): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_xyz'
main.f90:(.text+0x20b4): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x2145): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_xyz'
main.f90:(.text+0x217a): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x220b): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_xyz'
main.f90:(.text+0x2240): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x22d1): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_box'
main.f90:(.text+0x2372): undefined reference to `__gmxfort_utils_MOD_dihedral_angle'
main.f90:(.text+0x258f): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x25a9): undefined reference to `__gmxfort_trajectory_MOD_trajectory_close'
main.f90:(.text+0x25ea): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x2619): undefined reference to `__gmxfort_trajectory_MOD_trajectory_open'
main.f90:(.text+0x2624): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x2648): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_natoms'
main.f90:(.text+0x2876): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x289f): undefined reference to `__gmxfort_trajectory_MOD_trajectory_read_next'
main.f90:(.text+0x28e4): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x2964): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_xyz'
main.f90:(.text+0x2996): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x2a25): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_xyz'
main.f90:(.text+0x2a5a): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x2ae9): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_xyz'
main.f90:(.text+0x2b1e): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x2bad): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_xyz'
main.f90:(.text+0x2be2): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x2c73): undefined reference to `__gmxfort_trajectory_MOD_trajectory_get_box'
main.f90:(.text+0x2d14): undefined reference to `__gmxfort_utils_MOD_dihedral_angle'
main.f90:(.text+0x2f31): undefined reference to `__gmxfort_trajectory_MOD___vtab_gmxfort_trajectory_Trajectory'
main.f90:(.text+0x2f4b): undefined reference to `__gmxfort_trajectory_MOD_trajectory_close'
collect2: error: ld returned 1 exit status
Makefile:5: recipe for target 'all' failed
make: *** [all] Error 1

Thank you very much in advance

**Comment by clopasto** [comment]
Hi,
I checked the Makefile in ./example and this line is not working, at least in my distro:
   @gfortran main.f90 -I/usr/local/include `pkg-config --libs libgmxfort` -Wall
(not finding the dynamic libs?)
Using this alternative, it  works:

    @gfortran main.f90 -I/usr/local/include -L/usr/local/lib -Wall -lgmxfort

Then, just a note for use: the library is installed in /usr/local/lib, which may or may not be in the path variables of the distribution. If it is not, adding the path to LD_LIBRARY_PATH variables does the job:

> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

Then the code runs with
> ./a.out

Greetings,
Claudio

**Comment by wesbarnett** [comment]
The example was mainly intended to show how to include the `use` statements in a program to link to the library, but I admit that the existence of the Makefile may be confusing, since users will install the libraries to different locations (I actually install to `/usr/lib` and `/usr/include`.) I may just remove the Makefile or I'll have to consider how to document this.
