### ISSUE TITLE
Not working with the PGI compiler... any hints?

### ISSUE THREAD

**Issue by araquejc** [wesbarnett/libgmxfort#4]
Hi Wes, thanks for making this library available. I have been able to compile it and used with the gfortran compiler, but it doesn't work when I use the PGI compilers (pgfortran). I know this is kind of expected, but i was wondering if you might have any ideas about possible ways to make it work with PGI. I was hoping to use your libgmxfort library in my CUDA Fortran code. Thanks! JCA

Below is the output I get when I run the different tests after installation with pgfortran:

**$ cd libgmxfort/src/tests**

**$ ./../build/src/tests/xtcfile** 
Opened test.xtc for reading.
16500 atoms present in system.
101 frames present in trajectory file.
Frames saved: 101
Closed xtc file.
LIBGMXFORT ERROR:  is not in index file. The groups available are:
Warning: ieee_inexact is signaling
    1

**$ ../../build/src/tests/ndxfile** 
Opened test.xtc for reading.
16500 atoms present in system.
101 frames present in trajectory file.
Frames saved: 101
Closed xtc file.
Segmentation fault

**$ ../../build/src/tests/ndxfile_grp** 
Opened test.xtc for reading.
16500 atoms present in system.
101 frames present in trajectory file.
 
Segmentation fault

**$ ../../build/src/tests/read_next**   
Opened test.xtc for reading.
16500 atoms present in system.
101 frames present in trajectory file.
Frames saved: 100
LIBGMXFORT ERROR:  is not in index file. The groups available are:
    System (16500)
     Water (16500)
       SOL (16500)
      TEST (1)
        OW (4125)
     TEST2 (1)
Warning: ieee_inexact is signaling
    1

**$ ../../build/src/tests/utils**     
TEST  1: PASSED
TEST  2: PASSED
TEST  3: PASSED
TEST  4: PASSED
TEST  5: PASSED
TEST  6: PASSED
TEST  7: PASSED
Opened test.xtc for reading.
16500 atoms present in system.
101 frames present in trajectory file.
 
Segmentation fault

**Comment by araquejc** [comment]
@wesbarnett It seems to me that one of the issues when compiling with pgfortran is that when, for example, one calls `trj%x(1,1)`: 
- The "optional" `group` variable in `function trajectory_get_xyz(this, frame, atom, group)` is not recognized as "optional" in the merge call in line 283 of trajectory.f90. 
- Then, this triggers a call to `function indexfile_get(this, group_name, I)` with an empty `group_name` variable which, in turn, triggers the error message in line 228 in indexfile.f90.
- something similar seems to happen when calling `trj%natoms()` because the "optional" variable `group` in function `function trajectory_get_natoms(this, group)` behaves in the same way. But in this case one only gets the warning message in line 221 in indexfile.f90 (first time), then the warning is deactivated.

Could this be a compiler issue? It seems there are some other issues with using "optional" arguments  in PGI: [https://www.pgroup.com/userforum/viewtopic.php?t=7559&p=27296](url)  and [https://www.pgroup.com/userforum/viewtopic.php?t=7604](url)

What do you think?

BTW, I'm using the community version of PGI 19.10.

Thanks!

**Comment by wesbarnett** [comment]
It could be a compiler issue. it's been quite some time since I've used this, but when I did it was with `gfortran` and things worked. I am not familiar with PGI.

**Comment by araquejc** [comment]
@wesbarnett Thanks for your feedback! You are right, this is totally a compiler issue. I also compiled with `gfortran` and everything worked perfectly. So far, I was able to make it work with basic functionalities (first test) but I haven't figured the source of the segmentation fault for the rest of the tests. PGI's fortran is a a bit finicky for sure!
