### ISSUE TITLE
cmake meets an error

### ISSUE THREAD

**Issue by taipinghu** [wesbarnett/libgmxfort#5]
Dear,
when I compile the codes, an error occurs when cmake.
-- The Fortran compiler identification is GNU
-- Check for working Fortran compiler: /usr/bin/f95
-- Check for working Fortran compiler: /usr/bin/f95  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/f95 supports Fortran 90
-- Checking whether /usr/bin/f95 supports Fortran 90 -- yes
-- CMake build configuration for gmxfort 0.4.4
CMake Error at cmake/xdrfile.cmake:21 (find_package):
  By not providing "Findxdrfile.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "xdrfile", but
  CMake did not find one.

  Could not find a package configuration file provided by "xdrfile" with any
  of the following names:

    xdrfileConfig.cmake
    xdrfile-config.cmake

  Add the installation prefix of "xdrfile" to CMAKE_PREFIX_PATH or set
  "xdrfile_DIR" to a directory containing one of the above files.  If
  "xdrfile" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:38 (include)

-- Configuring incomplete, errors occurred!

How can I solve it?

Thanks a lot

**Comment by wesbarnett** [comment]
I would suggest using gfortran. I've not ever used this on Windows. I've only developed it on and used it on Linux. I'm about to put this project into read-only. I'm unable to support it any further.
